[window]
decorations = "buttonless"
opacity = 0.80
blur = true
startup_mode = "Windowed"
dynamic_title = true
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13.0

# Catppuccin Frappe (dark)
[colors]
[colors.primary]
background = "#303446"
foreground = "#c6d0f5"

[colors.normal]
black   = "#51576d"
red     = "#e78284"
green   = "#a6d189"
yellow  = "#e5c890"
blue    = "#8caaee"
magenta = "#f4b8e4"
cyan    = "#81c8be"
white   = "#b5bfe2"

[colors.bright]
black   = "#626880"
red     = "#e78284"
green   = "#a6d189"
yellow  = "#e5c890"
blue    = "#8caaee"
magenta = "#f4b8e4"
cyan    = "#81c8be"
white   = "#a5adce"

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"
unfocused_hollow = true
